# Generated by Django 5.1 on 2025-06-12 10:20

import common.mixins
import common.upload_to
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("specialists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_month",
                    models.CharField(
                        choices=[
                            (1, "Январь"),
                            (2, "Февраль"),
                            (3, "Март"),
                            (4, "Апрель"),
                            (5, "Май"),
                            (6, "Июнь"),
                            (7, "Июль"),
                            (8, "Август"),
                            (9, "Сентябрь"),
                            (10, "Октябрь"),
                            (11, "Ноябрь"),
                            (12, "Декабрь"),
                        ],
                        max_length=200,
                        verbose_name="Месяц начала",
                    ),
                ),
                ("start_year", models.SmallIntegerField(verbose_name="Год начала")),
                (
                    "end_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            (1, "Январь"),
                            (2, "Февраль"),
                            (3, "Март"),
                            (4, "Апрель"),
                            (5, "Май"),
                            (6, "Июнь"),
                            (7, "Июль"),
                            (8, "Август"),
                            (9, "Сентябрь"),
                            (10, "Октябрь"),
                            (11, "Ноябрь"),
                            (12, "Декабрь"),
                        ],
                        max_length=200,
                        null=True,
                        verbose_name="Месяц окончания",
                    ),
                ),
                (
                    "end_year",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Год окончания"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course", "Курс"),
                            ("college", "Колледж"),
                            ("univer", "Университет"),
                        ],
                        default="univer",
                        max_length=300,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "university",
                    models.CharField(max_length=300, verbose_name="Университет"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=300, verbose_name="Специализация"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        verbose_name="Диплом или сертификат",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="specialists.specialist",
                        verbose_name="Работник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образование",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_month",
                    models.CharField(
                        choices=[
                            (1, "Январь"),
                            (2, "Февраль"),
                            (3, "Март"),
                            (4, "Апрель"),
                            (5, "Май"),
                            (6, "Июнь"),
                            (7, "Июль"),
                            (8, "Август"),
                            (9, "Сентябрь"),
                            (10, "Октябрь"),
                            (11, "Ноябрь"),
                            (12, "Декабрь"),
                        ],
                        max_length=200,
                        verbose_name="Месяц начала",
                    ),
                ),
                ("start_year", models.SmallIntegerField(verbose_name="Год начала")),
                (
                    "end_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            (1, "Январь"),
                            (2, "Февраль"),
                            (3, "Март"),
                            (4, "Апрель"),
                            (5, "Май"),
                            (6, "Июнь"),
                            (7, "Июль"),
                            (8, "Август"),
                            (9, "Сентябрь"),
                            (10, "Октябрь"),
                            (11, "Ноябрь"),
                            (12, "Декабрь"),
                        ],
                        max_length=200,
                        null=True,
                        verbose_name="Месяц окончания",
                    ),
                ),
                (
                    "end_year",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Год окончания"
                    ),
                ),
                ("company", models.CharField(max_length=300, verbose_name="Компания")),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(to="core.stack", verbose_name="Стек"),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="specialists.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт работы",
                "verbose_name_plural": "Опыт работы",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Название проекта"),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        verbose_name="Постер",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на код проекта"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на проект"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лайки",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, to="core.stack", verbose_name="Стек"
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="specialists.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
            bases=(models.Model, common.mixins.WebpImageMixin),
        ),
        migrations.CreateModel(
            name="CommentProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "text",
                    models.TextField(max_length=5000, verbose_name="Текст комментария"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="specialists.commentproject",
                        verbose_name="Родительский комментарий",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_by_project",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="specialists.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к проекту",
                "verbose_name_plural": "Комментарии к проекту",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Минимальная зарплата"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Максимальная зарплата"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "руб"), ("USD", "долл"), ("EUR", "евро")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        choices=[
                            ("project", "Проектная работа"),
                            ("full_time", "Полная занятость"),
                            ("part_time", "Частичная занятость"),
                            ("temporary", "Временная работа"),
                            ("internship", "Стажировка"),
                        ],
                        default="full-time",
                        max_length=200,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активное резюме"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, to="core.stack", verbose_name="Стек"
                    ),
                ),
                (
                    "specialist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to="specialists.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
            },
        ),
        migrations.CreateModel(
            name="SpecialistContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("phone", "Телефон"),
                            ("email", "Почта"),
                            ("skype", "Skype"),
                            ("country", "Страна"),
                            ("city", "Город"),
                            ("address", "Адрес"),
                            ("other", "Другое"),
                        ],
                        max_length=300,
                        verbose_name="Тип контакта",
                    ),
                ),
                ("value", models.CharField(max_length=300, verbose_name="Значение")),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="specialists.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт специалиста",
                "verbose_name_plural": "Контакты специалистов",
            },
        ),
        migrations.CreateModel(
            name="SpecialistSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vk", "VK"),
                            ("tg", "Telegram"),
                            ("insta", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("other", "Другое"),
                        ],
                        max_length=300,
                        verbose_name="Тип социальной сети",
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Ссылка")),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="specialists.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть специалиста",
                "verbose_name_plural": "Социальные сети специалистов",
            },
        ),
    ]
