# Generated by Django 5.1 on 2025-06-16 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0003_companyrevie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(verbose_name="Дата и время собеседования"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн"),
                            ("offline", "Офлайн"),
                            ("phone", "Телефон"),
                        ],
                        default="online",
                        max_length=10,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Адрес/ссылка"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланировано"),
                            ("completed", "Завершено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="companies.jobapplication",
                        verbose_name="Отклик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собеседование",
                "verbose_name_plural": "Собеседования",
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
