# Generated by Django 5.1 on 2025-06-12 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobapplication",
            old_name="applicant",
            new_name="specialist",
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "specialist")},
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
