# Generated by Django 5.1 on 2025-06-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("backend", "Бэкенд"),
                            ("frontend", "Фронтенд"),
                            ("fullstack", "Фулстайк"),
                            ("analytics", "Аналитика"),
                            ("devops", "DevOps"),
                            ("design", "Дизайн"),
                            ("other", "Другое"),
                        ],
                        max_length=200,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": " Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Stack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": " Стек",
                "verbose_name_plural": "Стеки",
            },
        ),
    ]
